# Description of data sets from SCB

A significant amount of data from the registrars originates from Statistics Sweden (SCB).  This data is delivered in text format (file extension .txt), and is partitioned, for the most part, into individual files separated by both year and grouped data set.  While the data contained in this data originates from the specified data Registrars previously outlined, the data is received from SCB consolidated and grouped into various data sets which require further cleaning and processing.  These grouped data sets are described below. 


## Population

Description of Population data set

## Lisa

Description of Lisa data set

## Housing

Description of Housing data set




# Data cleaning and joining of data

As illustrated above, the data from RELOC-AGE is comprised of from several registers and sources.  In order to arrive at the final data set, a number of data cleaning actions, multiple joins, and many quality control steps have been taken to insure reliable analysis and data integrity.  This section details steps taken.

## SCB data

With data covering about 3 million individuals over a period of decades and consisting of multitude of variables contained in hundreds of very large files, the computational effort to complete these joins are very time intensive, often taking hours for each merge, with progress occasionally hindered by computational restrictions and small errors which arise in the data cleaning process.  With this in mind, detailed documentation, contained both here and alongside code used in the data cleaning, is prioritized to reduce any need to repeat these time-intensive processes. 

As a first step, the following initial data cleaning is perfomred:


* Raw data files are organized into folder structure where each folder contains all data from a particular data set.
* An individual script for each data set is written in R that reads the raw yearly .txt files and merges files into one data set.
* When required, a variable "year" is generated in the joined data set specifying which year the data originates from( taken from the name of the .txt file).
* Variables are renamed into lowercase with spaces and other delimiters transformed into underscores ( _ ) for consistent naming conventions and avoidance of future merge conflicts.
* The joined and cleaned data set is saved in the contained folder in both R's .rds and Stata's .dta formats.
* A README.txt file is created in each folder documenting the process.

The result consists of eleven folders each containing a data set's respective raw data, a documented R merging/cleaning script for full reproducibility, and a merged data set in both R and Stata format to be used in subsequent merging and further analysis.





